AWSTemplateFormatVersion: 2010-09-09
Description: |
  This CFN launches an EC2 with an Apache Server and a Kitten Web site
Resources:
  KittenWebEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a8b4cd432b1c3063 # most recent ami id of Amazon Linux2
      InstanceType: t2.micro
      KeyName: burakawskey # pem file name without extension
      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref HTMLSecurityGroup
      UserData: 
         Fn::Base64:
                |
             #!/bin/bash
             yum update -y
             yum install httpd -y
             FOLDER="https://raw.githubusercontent.com/BurakKoban/my-portfolio_rep/main/Project-101-kittens-carousel-static-website-ec2/static-web"            
             wget ${FOLDER}/index.html /var/www/html/
             wget ${FOLDER}/cat0.jpg /var/www/html/
             wget ${FOLDER}/cat1.jpg /var/www/html/
             wget ${FOLDER}/cat2.jpg /var/www/html/
             wget ${FOLDER}/cat3.png /var/www/html/
             systemctl start httpd
             systemctl enable httpd
      Tags:
        - Key: Name
          Value: CFN-Web Server of Kitten Web
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0

  HTMLSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTML access via port 80
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0