apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  labels:
    name: web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      name: web-pod
  template:
    metadata:
      labels:
        name: web-pod
    spec:
      containers:
        - name: web-app
          image: burakkoban/web-server
          ports:
            - containerPort: 80
          env:
          - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: mysql-admin-password
          envFrom:
          - configMapRef:
              name: servers-configmap